services:
  web:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BASE_PATH=${VITE_BASE_PATH}
  api:
    build: ./backend
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_URL: mongodb://db/test
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-express:/data/db

volumes:
  mongo-express: